sudo: required

services:
  - docker

env:
  DOCKER_COMPOSE_VERSION: 1.13.0

install:
  - sudo rm /usr/local/bin/docker-compose
  - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin

script: docker-compose run -e REDIS_HOST=redis socket-redis ./script/test.sh

deploy:
  - provider: npm
    email: tech@cargomedia.ch
    api_key:
      secure: $NPM_API_KEY
    on:
      tags: true
      repo: cargomedia/socket-redis
  - provider: script
    script: ./script/docker-push.sh
    on:
      tags: true
      repo: zazabe/socket-redis
